language: java

sudo: false

matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk11
    
addons:
  apt:
    packages:
      - oracle-java8-installer

script: ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew sonar
