language: java

sudo: false

env:
  - ORG_GRADLE_PROJECT_skipSigning=yes
  
matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk11
    
addons:
  apt:
    packages:
      - oracle-java8-installer

script: ./gradlew check jacocoTestReport codeCoverageReport sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
